// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTUIYTZUNMjLCBYby2aFfxBPrWKrjrGQE',
    appId: '1:1081636730361:web:b2f895f04828b1d0cdf928',
    messagingSenderId: '1081636730361',
    projectId: 'glady-ce3fe',
    authDomain: 'glady-ce3fe.firebaseapp.com',
    storageBucket: 'glady-ce3fe.firebasestorage.app',
    measurementId: 'G-1XL28LWML3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr3Z-btuXNWGFTzDexu92fL8sHbyKgulE',
    appId: '1:1081636730361:android:ac428b9227402491cdf928',
    messagingSenderId: '1081636730361',
    projectId: 'glady-ce3fe',
    storageBucket: 'glady-ce3fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpbz5sdga1WSs_8SNdlN85ssAaTAUTTHs',
    appId: '1:1081636730361:ios:8b55a64143ce95a3cdf928',
    messagingSenderId: '1081636730361',
    projectId: 'glady-ce3fe',
    storageBucket: 'glady-ce3fe.firebasestorage.app',
    iosBundleId: 'com.example.fullNodeChatApp',
  );
}
